{% set name = "simple-dftd3" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awvwgk/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4bef311f8e5a2c32141eddeea65615c3c8480f917cd884488ede059fb0962a50
  patches:
    - wrap.patch

build:
  number: 0
  script:
    - set -ex  # [unix]
    - mv $PREFIX/lib/pkgconfig/blas.pc $SRC_DIR  # [unix]
    - >
       meson setup _build
       ${MESON_ARGS:---prefix=${PREFIX} --libdir=lib}  # [unix]
       --prefix=%LIBRARY_PREFIX% --pkg-config-path=%PREFIX%\lib\pkgconfig  # [win]
       --buildtype=release
       -Dblas=custom -Dblas_libs=blas  # [unix]
    - meson compile -C _build
    - meson test -C _build --no-rebuild --print-errorlogs  # [build_platform == target_platform]
    - meson install -C _build --no-rebuild
    - mv $SRC_DIR/blas.pc $PREFIX/lib/pkgconfig  # [unix]

  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - meson
    - ninja
    - asciidoctor  # [unix]
    - pkg-config
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - libblas  # [unix]
    - mctc-lib
    - toml-f

test:
  requires:
    - pkg-config
  commands:
    - s-dftd3 --version
    - test -f $PREFIX/lib/libs-dftd3$SHLIB_EXT  # [unix]
    - set PKG_CONFIG_PATH=%PREFIX%\lib\pkgconfig  # [win]
    - pkg-config s-dftd3 --exact-version {{ version }}

about:
  home: https://github.com/awvwgk/simple-dftd3
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Simple reimplementation of the DFT-D3 model
  doc_url: https://awvwgk.github.io/simple-dftd3/

extra:
  recipe-maintainers:
    - awvwgk
