{% set name = "simple-dftd3" %}
{% set version = "1.3.2" %}

package:
  name: {{ name }}-pkg
  version: {{ version }}

source:
  url: https://github.com/dftd3/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: bbf6aaa23332a7217a6dfc5c3ca8dc74f949c4cb6e4dccbadf32fa21fe8bb0d7

build:
  number: 0

outputs:
  - name: {{ name }}
    script: build_pkg.sh  # [unix]
    script: build_pkg.bat  # [win]
    build:
      string: {{ module_abi }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
      run_exports:
        - {{ pin_subpackage(name, max_pin='x.x') }}

    requirements:
      build:
        - {{ stdlib('c') }}  # [unix]
        - {{ stdlib('m2w64_c') }}  # [win]
        - {{ compiler('c') }}  # [unix]
        - {{ compiler('fortran') }}  # [unix]
        - {{ compiler('m2w64_c') }}  # [win]
        - {{ compiler('m2w64_fortran') }}  # [win]
        - meson
        - ninja
        - pkg-config
        - llvm-openmp  # [osx]
      host:
        - libgomp  # [linux]
        - llvm-openmp  # [osx]
        - mctc-lib-devel * {{ module_abi }}_*
        - toml-f-devel * {{ module_abi }}_*
      run:
        - llvm-openmp  # [osx]

    test:
      requires:
        - pkg-config
      commands:
        - s-dftd3 --version
        - pkg-config s-dftd3 --exact-version {{ version }}
        - test -f $PREFIX/lib/libs-dftd3$SHLIB_EXT  # [unix]
        - test ! -f $PREFIX/lib/libs-dftd3.a  # [unix]

  - name: {{ name }}-devel
    build:
      string: {{ module_abi }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
      run_exports:
        - {{ pin_subpackage(name, max_pin='x.x') }} {{ module_abi }}_*

    requirements:
      run:
        - {{ pin_subpackage(name, max_pin='x.x') }} {{ module_abi }}_*

    test:
      requires:
        - pkg-config
      commands:
        - s-dftd3 --version
        - pkg-config s-dftd3 --exact-version {{ version }}
        - test -f $PREFIX/lib/libs-dftd3$SHLIB_EXT  # [unix]
        - test ! -f $PREFIX/lib/libs-dftd3.a  # [unix]

about:
  home: https://dftd3.readthedocs.io
  license: LGPL-3.0-or-later
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Simple reimplementation of the DFT-D3 model
  dev_url: https://github.com/dftd3/simple-dftd3
  doc_url: https://dftd3.github.io/simple-dftd3/

extra:
  recipe-maintainers:
    - awvwgk
  feedstock-name: {{ name }}
