{% set name = "simple-dftd3" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dftd3/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 20adc61ed606e71227a78308a9ddca34d822d46117e6311ed51a00df16b2eabc
  patches:
    - wrap.patch

build:
  number: 0
  skip: true  # [win]

  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}  # [unix]
    - {{ stdlib("c") }}    # [unix]
    - {{ compiler('fortran') }}  # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - meson
    - ninja
    - asciidoctor  # [unix]
    - pkg-config
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - mctc-lib
    - toml-f

test:
  requires:
    - pkg-config
  commands:
    - s-dftd3 --version
    - test -f $PREFIX/lib/libs-dftd3$SHLIB_EXT  # [unix]
    - set PKG_CONFIG_PATH=%PREFIX%\lib\pkgconfig  # [win]
    - pkg-config s-dftd3 --exact-version {{ version }}

about:
  home: https://dftd3.readthedocs.io
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
  summary: Simple reimplementation of the DFT-D3 model
  dev_url: https://github.com/dftd3/simple-dftd3
  doc_url: https://dftd3.github.io/simple-dftd3/

extra:
  recipe-maintainers:
    - awvwgk
