{% set name = "simple-dftd3" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awvwgk/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3c198cc52fc82c08668656f9b035921a334a372a5e1a7ee9a2b30cae5c13c657
  patches:
    - disable-ffibuilder.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - meson 0.55.*
    - ninja
    - asciidoctor
  host:
    - libblas
    - llvm-openmp  # [osx]
    - libgomp  # [linux and not aarch64]
  run:
    - libblas

test:
  commands:
    - s-dftd3 --version

about:
  home: https://github.com/awvwgk/simple-dftd3
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - "COPYING"
    - "COPYING.LESSER"
  summary: 'Simple reimplementation of the DFT-D3 model'
  doc_url: https://awvwgk.github.io/simple-dftd3/

extra:
  recipe-maintainers:
    - awvwgk
