{% set name = "simple-dftd3" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/awvwgk/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 79b507a0d892f19222e1403f4c7ebb98ce9eb96b3b8d4821ba5631aa9ac756be
  patches:
    - disable-ffibuilder.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - meson 0.55.*
    - ninja
    - asciidoctor
  host:
    - libblas
    - llvm-openmp  # [osx]
    - libgomp  # [linux and not aarch64]
  run:
    - libblas

test:
  commands:
    - s-dftd3 --version

about:
  home: https://github.com/awvwgk/simple-dftd3
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - "COPYING"
    - "COPYING.LESSER"
  summary: 'Simple reimplementation of the DFT-D3 model'
  doc_url: https://awvwgk.github.io/simple-dftd3/

extra:
  recipe-maintainers:
    - awvwgk
